### PR TITLE
Kedro text preprocess

### PR DESCRIPTION
**Pull request by issacj-17**
## Update extractor.py
- Amended extract_links to ignore footnotes and online forms
- Replace En Dash with dash to extract these dashes into `extracted_content_body`
- Implemented extract_tables method to extract tables as a 3d array (list of 2d tables)

## Update utils.py
- Created function that is able to flag articles that contains the given keyword. The flag is stored as a separate column

## Update nodes.py
- Added `extracted_tables` as new column to merged_data
- Implemented a statement that flags recipe articles as true in `is_recipe` column

## Update README.md
- Updated columns to include extracted_tables and is_recipe

### CODE REVIEW

**Comment by issacj-17** [comment]
@Wilsven @jwyting @sixiannn @jzkoh I have implemented a few changes to the text extraction pipeline. 

- The extracted links should now ignore footnotes (there was a bug in the previous implementation) and online forms.
- Also, I have resolved the issue with the En Dash which was removed when cleaned. It is probably due to the fact that it does not exist as an ascii representation.
- Tables are now extracted as a nested list (list[list[list[str]]])
- I am able to flag recipe articles by performing a keyword search across a few columns

**Comment by issacj-17** [comment]
Whitelisting is not a part of this pull request as we need to look at how our code is implemented to extract the content body of articles that were considered as removed and to include the content body of articles that have exceeded the Excel character limit.

**Comment by Wilsven** [comment]
@issacj-17 What's the update on the articles meant to be unflagged and added back?

**Comment by Wilsven** [comment]
Thanks a lot for your overview above. I will take a look at them. 

In any case, I have done a very brief comparison with the articles you had flagged as recipes vs the articles clustered in my topic modelling work. It would seem there are **quite a number of recipe articles you have missed out.** 

I understand that Juan Zhen mentioned precision is more important than the recall but if so, I am doubtful about the efficacy and most importantly, the purpose of flagging recipe articles with low recall. Since I am away for the rest of this week, I hope you can follow up with @jzkoh on this more to understand the situation and problem better.  

Please refer to this [comment](https://trello.com/c/V6Z7nKqh/117-feature-extraction-topics-modelling#:~:text=%40issacjoseignatius%20Please%20open,cc%3A%20%40juanzhenkoh) in Trello. Also, do download the HTML file. It contains a visulization of the clustering from the topic modelling work I have done. Please focus on cluster 6. Do refer to the comment for more information. 

Thanks!

**Comment by Wilsven** [comment]
I will leave this PR open for now. The objective for the flagging of recipe articles is currently unclear and I do not want to integrate that portion of the code into the `main` branch until we have a better understanding of what is required. 

Feel free to make another PR for the other changes and fixes.

**Comment by issacj-17** [comment]
@Wilsven I am going to close this pull request and raise this as an issue instead as I am making changes to the pipeline. There are other features that need to be integrated into the text processing pipeline.

**Pull request closed without merging**
